{{
  config(
    materialized='view',
    alias='stg_tickets',
    tags=['helpdesk', 'tickets', 'staging', 'debug'],
  )
}}

with raw_source as (
  select `id`, `parent_id`, `entity_id`, `description`, `ticket_category_id`, `person_id`, `place_id`, `data`, `created_at`, `updated_at`, `deleted_at`, `service_id`, `contract_id`, `time_zone`, `status_id`, `graph_group_id`, `case`, `title`, `channel`, `priority`, `impact`, `urgency`, `number`, `user_group_id`, `responsible_user_id`, `closure_code`, `deadline`, `ext_number`, `actual_status_id`, `last_comment_id`, `closed_status_id`, `client_bill_sum`, `supplier_bill_sum`, `last_todo_id`, `resolved_status_id`, `bpm_code`, `mass_type`, `mass_head_id`, `status_data_collection_at`, `status_device_reconfiguration_at`, `status_wating_of_delivery_to_at`, `status_remote_activation_at`, `status_return_approval_at`, `status_wating_of_delivery_from_at`, `status_signing_acts_at`, `status_verification_of_acts_at`, `status_work_complited_at`, `status_received_for_service_center_at`, `status_device_activation_at`, `crpt_state`, `status_cant_calling_at`, `ticket_case_id`, `user_group_cycle_count`, `channel_id`, `partner_code`
  from {{ s3_parquet_run('helpdesk', 'tickets', '`id` String, `parent_id` String, `entity_id` String, `description` Nullable(String), `ticket_category_id` String, `person_id` String, `place_id` String, `data` Nullable(String), `created_at` String, `updated_at` String, `deleted_at` String, `service_id` String, `contract_id` String, `time_zone` Nullable(String), `status_id` String, `graph_group_id` String, `case` Nullable(String), `title` Nullable(String), `channel` Nullable(String), `priority` Nullable(Int32), `impact` Nullable(Int32), `urgency` Nullable(Int32), `number` Nullable(Int32), `user_group_id` String, `responsible_user_id` String, `closure_code` String, `deadline` String, `ext_number` Nullable(String), `actual_status_id` String, `last_comment_id` String, `closed_status_id` String, `client_bill_sum` Nullable(Decimal(12,2)), `supplier_bill_sum` Nullable(Decimal(12,2)), `last_todo_id` String, `resolved_status_id` String, `bpm_code` Nullable(String), `mass_type` Nullable(String), `mass_head_id` String, `status_data_collection_at` String, `status_device_reconfiguration_at` String, `status_wating_of_delivery_to_at` String, `status_remote_activation_at` String, `status_return_approval_at` String, `status_wating_of_delivery_from_at` String, `status_signing_acts_at` String, `status_verification_of_acts_at` String, `status_work_complited_at` String, `status_received_for_service_center_at` String, `status_device_activation_at` String, `crpt_state` Nullable(String), `status_cant_calling_at` String, `ticket_case_id` String, `user_group_cycle_count` Nullable(Int32), `channel_id` String, `partner_code` Nullable(String)') }}
)
select
  assumeNotNull(CAST(toUUIDOrNull(nullIf(trimBoth(toString(`id`)), '')), 'Nullable(UUID)')) AS `id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`parent_id`)), '')), 'Nullable(UUID)') AS `parent_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`entity_id`)), '')), 'Nullable(UUID)') AS `entity_id`,
  CAST(`description`, 'Nullable(String)') AS `description`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`ticket_category_id`)), '')), 'Nullable(UUID)') AS `ticket_category_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`person_id`)), '')), 'Nullable(UUID)') AS `person_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`place_id`)), '')), 'Nullable(UUID)') AS `place_id`,
  CAST({{ ch_json_from_string("nullIf(trimBoth(toString(`data`)), '')") }}, 'Nullable(JSON)') AS `data`,
  CAST(coalesce(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`created_at`)), ''), 3), toDateTime64('1970-01-01 00:00:00', 3)), 'DateTime64(3)') AS `created_at`,
  CAST(coalesce(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`updated_at`)), ''), 3), toDateTime64('1970-01-01 00:00:00', 3)), 'DateTime64(3)') AS `updated_at`,
  CAST({{ ch_parse_deleted_at_or_null('`deleted_at`') }}, 'Nullable(DateTime64(3))') AS `deleted_at`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`service_id`)), '')), 'Nullable(UUID)') AS `service_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`contract_id`)), '')), 'Nullable(UUID)') AS `contract_id`,
  CAST(`time_zone`, 'Nullable(String)') AS `time_zone`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`status_id`)), '')), 'Nullable(UUID)') AS `status_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`graph_group_id`)), '')), 'Nullable(UUID)') AS `graph_group_id`,
  CAST(`case`, 'Nullable(String)') AS `case`,
  CAST(`title`, 'Nullable(String)') AS `title`,
  CAST(`channel`, 'Nullable(String)') AS `channel`,
  CAST(`priority`, 'Nullable(Int32)') AS `priority`,
  CAST(`impact`, 'Nullable(Int32)') AS `impact`,
  CAST(`urgency`, 'Nullable(Int32)') AS `urgency`,
  assumeNotNull(CAST(`number`, 'Nullable(Int32)')) AS `number`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`user_group_id`)), '')), 'Nullable(UUID)') AS `user_group_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`responsible_user_id`)), '')), 'Nullable(UUID)') AS `responsible_user_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`closure_code`)), '')), 'Nullable(UUID)') AS `closure_code`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`deadline`)), ''), 3), 'Nullable(DateTime64(3))') AS `deadline`,
  CAST(`ext_number`, 'Nullable(String)') AS `ext_number`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`actual_status_id`)), '')), 'Nullable(UUID)') AS `actual_status_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`last_comment_id`)), '')), 'Nullable(UUID)') AS `last_comment_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`closed_status_id`)), '')), 'Nullable(UUID)') AS `closed_status_id`,
  CAST(`client_bill_sum`, 'Nullable(Decimal(12,2))') AS `client_bill_sum`,
  CAST(`supplier_bill_sum`, 'Nullable(Decimal(12,2))') AS `supplier_bill_sum`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`last_todo_id`)), '')), 'Nullable(UUID)') AS `last_todo_id`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`resolved_status_id`)), '')), 'Nullable(UUID)') AS `resolved_status_id`,
  CAST(`bpm_code`, 'Nullable(String)') AS `bpm_code`,
  CAST(`mass_type`, 'Nullable(String)') AS `mass_type`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`mass_head_id`)), '')), 'Nullable(UUID)') AS `mass_head_id`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_data_collection_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_data_collection_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_device_reconfiguration_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_device_reconfiguration_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_wating_of_delivery_to_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_wating_of_delivery_to_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_remote_activation_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_remote_activation_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_return_approval_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_return_approval_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_wating_of_delivery_from_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_wating_of_delivery_from_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_signing_acts_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_signing_acts_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_verification_of_acts_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_verification_of_acts_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_work_complited_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_work_complited_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_received_for_service_center_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_received_for_service_center_at`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_device_activation_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_device_activation_at`,
  CAST(`crpt_state`, 'Nullable(String)') AS `crpt_state`,
  CAST(parseDateTime64BestEffortOrNull(nullIf(trimBoth(toString(`status_cant_calling_at`)), ''), 3), 'Nullable(DateTime64(3))') AS `status_cant_calling_at`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`ticket_case_id`)), '')), 'Nullable(UUID)') AS `ticket_case_id`,
  CAST(`user_group_cycle_count`, 'Nullable(Int32)') AS `user_group_cycle_count`,
  CAST(toUUIDOrNull(nullIf(trimBoth(toString(`channel_id`)), '')), 'Nullable(UUID)') AS `channel_id`,
  CAST(`partner_code`, 'Nullable(String)') AS `partner_code`
from raw_source
